name: ecommerce
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  mime: ^1.0.5
  path: ^1.8.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/        
    - assets/images/chick_logo.png

